### ISSUE TITLE
Doesn't pause at a fullstop (period).

### ISSUE THREAD

**Issue by eouthwaite** [sajacy/textnarrator-chrome-extension#1]
Hi, nice initial release - one slight criticism is that it doesn't pause at the end of a sentence

**Comment by eouthwaite** [comment]
P.S. I was getting the extension to read this page:  http://docs.marklogic.com/guide/app-dev/appdev on the much-beloved Windows 8.1

**Comment by sajacy** [comment]
Thanks for filing an issue!  I've also experienced this phenomenon, and
seen it reported on other text-to-speech extensions.  It seems to be a
"feature" of Chrome's native TTS module.  This is one of the major issues
I'll be tackling with a second release.
